import Head from "next/head";
import NavBar from "../common/NavBar";
import Header from "../common/Header";
import Image from "next/image";;
import Footer from "../common/Footer";
import {FunctionComponent, PropsWithChildren} from "react";
type props = {
    pageTitle : string
}
const PageLayout : FunctionComponent<PropsWithChildren<props>> = ({children,pageTitle}) => {
    return (
        <>
            <div className="page-layout mx auto max-w-7xl  space-y-8 sm:px-6 lg:px-8">
                <Head>
                    <title>{pageTitle}</title>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="icon" href="/favicon.ico" />
                </Head>
                    <div className="relative z-10 bg-white pb-8  lg:w-full lg:max-w-2xl">
                        <NavBar/>
                </div>
                <div className="py-4 md:py-6 lg:py-8  sm:px-6 lg:max-w-7xl lg:px-8">
                    {children}
                </div>
            </div>
            <Footer/>
        </>
    )
}

export default PageLayout